<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add new album';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php

// This provides a default CSS class and placeholder text for the title element:
$album = $this->form->get('title');
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Album title');

// This provides a default CSS class and placeholder text for the artist element:
$artist = $this->form->get('artist');
$artist->setAttribute('class', 'form-control');
$artist->setAttribute('placeholder', 'Artist');

// This provides CSS classes for the submit button:
$submit = $this->form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$this->form->setAttribute('action', $this->url('album', ['action' => 'add']));
$this->form->prepare();
/*
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('id'));
echo $this->formRow($this->form->get('title'));
echo $this->formRow($this->form->get('artist'));
echo $this->formSubmit($this->form->get('submit'));
//echo $this->formCollection($this->form); // this render all the form automatically
echo $this->form()->closeTag();
*/

?>

<?php /* Advanced form rendering */ ?>
<?php echo $this->form()->openTag($this->form); ?>
<?php
// Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within
?>
    <div class="form-group">
        <?= $this->formLabel($album) ?>
        <?= $this->formElement($album) ?>
        <?= $this->formElementErrors()->render($album, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($artist) ?>
        <?= $this->formElement($artist) ?>
        <?= $this->formElementErrors()->render($artist, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($this->form->get('id'));
echo $this->form()->closeTag();