<?php
use Backend\Form\GenreForm;
?>

<h1>Genre</h1>

<?php if ($this->errorMessage !== ''): ?>
    <div class="alert alert-danger" role="alert">
        <?= $this->errorMessage ?>
    </div>
<?php endif; ?>

<?php
/** @var GenreForm $form */

$form = $this->form;

$id = $form->get('id');
$id->setAttribute('class', 'form-control');
$id->setAttribute('type', 'text');

$form->setAttribute('action', $this->url('backend/genre/' . (is_null($this->entityId) ? 'add' : 'edit'), ['id' => $this->entityId]));

$title = $form->get('title');
$title->setAttribute('class', 'form-control');
$title->setAttribute('placeholder', 'Title');

$slug = $form->get('slug');
$slug->setAttribute('class', 'form-control');
$slug->setAttribute('placeholder', 'Slug');

$description = $form->get('description');
$description->setAttribute('class', 'form-control');
$description->setAttribute('placeholder', 'Description');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary mr-1');

$submit_and_new = $form->get('submit_and_new');
$submit_and_new->setAttribute('class', 'btn btn-primary mr-1');

$form->prepare();
?>

<?php if (is_null($this->entityId)): ?>
    <h3>Add entity</h3>
<?php else: ?>
    <h3>Edit entity</h3>
<?php endif; ?>

<?= $this->form()->openTag($form) ?>

<fieldset>
    <div class="form-group">
        <?= $this->formLabel($title) ?>
        <?= $this->formElement($title) ?>
        <?=
        $this->formElementErrors()
            ->setMessageOpenFormat('<small class="form-text text-danger">')
            ->setMessageCloseString('</small>')
            //->render($id, ['class' => 'form-text text-muted'])
            ->render($title)
        ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($slug) ?>
        <?= $this->formElement($slug) ?>
        <?=
        $this->formElementErrors()
            ->setMessageOpenFormat('<small class="form-text text-danger">')
            ->setMessageCloseString('</small>')
            ->render($slug)
        ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($description) ?>
        <?= $this->formElement($description) ?>
        <?=
        $this->formElementErrors()
            ->setMessageOpenFormat('<small class="form-text text-danger">')
            ->setMessageCloseString('</small>')
            //->render($id, ['class' => 'form-text text-muted'])
            ->render($description)
        ?>
    </div>
</fieldset>

<?= $this->formSubmit($submit) ?>
<?= is_null($this->entityId) ? $this->formSubmit($submit_and_new) : '' ?>
<?= $this->formHidden($form->get('id')) ?>
<?= $this->form()->closeTag() ?>