<?php

/**
 * @var $item \App\Model\Author
 */

$title = 'Authors list';
//$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('backend/author/add') ?>">Add new author</a>
</p>

<table class="table">
    <tr>
        <th>id</th>
        <th>name</th>
        <th>action</th>
    </tr>
    <?php foreach ($this->items as $item) : ?>
        <tr>
            <td><?= $this->escapeHtml($item->id) ?></td>
            <td>
                <?= $this->escapeHtml($item->name) ?>
                <br/>
                <small class="text-muted"><?= $this->escapeHtml($item->slug) ?></small>
            </td>
            <td>
                <a href="<?= $this->url('backend/author/edit', ['id' => $item->id,]) ?>">Edit</a>
                <a href="<?= $this->url('backend/author/delete', ['id' => $item->id,]) ?>"
                   onclick="return confirm('Are you sure ?');">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<?= $this->paginationHtml ?>