<?php

use App\ViewHelper\Date as DateViewHelper;
use App\Helper\QueryString as QueryStringHelper;

/**
 * @var $layout \Laminas\View\Model\ViewModel
 * @var $item \App\Model\Author
 */

$layout = $this->layout();

$title = 'Authors list';
//$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
    <p>
        <a href="<?= $this->url('backend/author/add') ?>">Add new Author</a>
    </p>
    <table class="table">
        <tr>
            <th><?= $this->sortableColumnName($layout->queryString, $layout->orderBy, 'id', 'id', $layout->defaultOrderBy) ?></th>
            <th><?= $this->sortableColumnName($layout->queryString, $layout->orderBy, 'name', 'name', $layout->defaultOrderBy) ?></th>
            <th><?= $this->sortableColumnName($layout->queryString, $layout->orderBy, 'total Books', 'books_count', $layout->defaultOrderBy) ?></th>
            <th><?= $this->sortableColumnName($layout->queryString, $layout->orderBy, 'date added', 'created_at', $layout->defaultOrderBy) ?></th>
            <th><?= $this->sortableColumnName($layout->queryString, $layout->orderBy, 'date updated', 'updated_at', $layout->defaultOrderBy) ?></th>
            <th>action</th>
        </tr>
        <?php foreach ($this->items as $item) : ?>
            <tr>
                <td><?= $this->escapeHtml($item->id) ?></td>
                <td>
                    <?= $this->escapeHtml($item->name) ?>
                    <br/>
                    <small class="text-muted"><?= $this->escapeHtml($item->slug) ?></small>
                </td>
                <td><?= $item->books->count() ?></td>
                <td><?= $this->date($item->created_at->timestamp, DateViewHelper::FORMAT_ADMIN_SIMPLE) ?></td>
                <td><?= $this->date($item->updated_at->timestamp, DateViewHelper::FORMAT_ADMIN_SIMPLE) ?></td>
                <td>
                    <?= $this->partial('backend/partial/gridActions', [
                        'actions' => [
                            [
                                'type' => 'edit',
                                'href' => $this->url('backend/author/edit', ['id' => $item->id,]),
                                'class' => 'btn btn-outline-warning',
                                'alt' => 'Edit',
                                'text' => '',
                                'icon' => 'far fa-edit',
                                'confirm' => false,
                            ],
                            [
                                'type' => 'delete',
                                'href' => $this->url('backend/author/delete', ['id' => $item->id,]),
                                'class' => 'btn btn-outline-danger',
                                'alt' => 'Delete',
                                'text' => '',
                                'icon' => 'far fa-trash-alt',
                                'confirm' => true,
                            ],
                        ],
                    ]); ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>

<?= $this->paginationHtml ?>